seperate windows installer and portable

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -141,14 +141,6 @@ jobs:
         - name: Build for Windows
           run: pyinstaller build_resources/main_windows.spec
         - if: ${{ github.event_name != 'pull_request' }}
-          name: Upload Windows Artifact (Portable EXE)
-          uses: actions/upload-artifact@v5
-          with:
-            name: wonky-window-windows-portable
-            path: "dist/Wonky Window.exe"
-            retention-days: 7
-            if-no-files-found: error
-        - if: ${{ github.event_name != 'pull_request' }}
           name: Compile .ISS to .EXE Installer
           uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
           with:
@@ -160,6 +152,50 @@ jobs:
           with:
             name: wonky-window-windows-installer
             path: output/WonkyWindow-Setup.exe
+            retention-days: 7
+            if-no-files-found: error
+
+    build-windows-portable:
+        runs-on: windows-latest
+        steps:
+        - uses: actions/checkout@v5
+        - uses: actions/setup-python@v6
+          with:
+            python-version: "3.12"
+            cache: "pip"
+            cache-dependency-path: requirements.txt
+        - run: pip install -r ./requirements.txt
+        - name: Read version
+          id: version
+          shell: bash
+          run: |
+            test -s VERSION || { echo "VERSION file missing/empty"; exit 1; }
+            echo "version=$(tr -d '\r' < VERSION | sed 's/^v//')" >> "$GITHUB_OUTPUT"
+
+        - name: Create version info
+          shell: bash
+          env:
+            VER: ${{ steps.version.outputs.version }}
+          run: |
+            echo "VSVersionInfo(
+              ffi=FixedFileInfo(
+                filevers=(${VER//./,},0),
+                prodvers=(${VER//./,},0)
+              ),
+              kids=[StringFileInfo([StringTable('040904B0', [
+                StringStruct('FileDescription', 'Wonky Window'),
+                StringStruct('FileVersion', '$VER'),
+                StringStruct('ProductName', 'Wonky Window'),
+                StringStruct('ProductVersion', '$VER')
+              ])])]
+            )" > version_info.txt
+        - name: Build for Windows
+          run: pyinstaller build_resources/main_windows_portable.spec
+        - name: Upload Windows Artifact (Portable)
+          uses: actions/upload-artifact@v5
+          with:
+            name: wonky-window-windows-portable
+            path: "dist/Wonky Window/**"
             retention-days: 7
             if-no-files-found: error
             
